version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27000:27017"
    volumes:
      - mongo_data:/data/db
      - ./imp:/imp

  backend:
    image: backend:1.0
    ports:
      - "8000:8000"
    environment:
      - MONGO=mongodb://mongodb:27017
    depends_on:
      - mongodb

  nginx:
    container_name: nginx-1
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  static_volume:
