name: Build and Deploy Frontend

on:
  workflow_dispatch: # Позволяет запускать вручную
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          if [ "${{ github.ref }}" == "refs/tags/"* ]; then
            DEPLOY_DIR=stable-frontend
          else
            DEPLOY_DIR=latest-frontend
          fi

          scp -r dist/* ec2-user@${{ secrets.EC2_HOST }}:/path/to/$DEPLOY_DIR
